[package]
name = "cyrene-audio-seeker"
version = "26.1.0"
description = "Cyrene音频检索器 - 音频指纹检索工具"
license = "GPL-3.0-or-later"
repository = "https://github.com/Cyrene2008/AudioSeeker"
homepage = "https://github.com/Cyrene2008/AudioSeeker"
edition = "2021"

[lib]
name = "cyrene_audio_seeker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools", "protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
casi-server = { path = "../crates/casi-server" }
